### ISSUE TITLE
use `morpheus-graphql.core` for dynamic resolving

### ISSUE THREAD

**Issue by nalchevanidze** [theobat/massalia#1]
use `morpheus-graphql.core` . 

1. is lightweight

2. you can define `graphql-api` without real haskell types.

```hs
gqlSchema :: Applicative m => ResponseStream e m Schema
gqlSchema =
  schemaFromTypeDefinitions
    [dsl|
  
  type Query {
    deity(name: String): Deity!
  }

  type Deity {
    name: String!
    power: [String!]!
  }
|]
```
you can:
- convert schema `graphqlSchema->sqlSchema`.
- according to schema + selection generate sql query and build `RootResModel e m`

```hs
resolver :: Monad m => RootResModel e m
resolver =
  RootResModel
    { query =
        pure $
          ResObject
            ( ObjectResModel
                { __typename = "Query",
                  objectFields =
                    [ ( "deity",
                        pure
                          $ ResObject
                          $ ObjectResModel
                            { __typename = "Deity",
                              objectFields =
                                [ ( "name",
                                    pure $ string "Morpheus"
                                  ),
                                  ( "power",
                                    pure $
                                      ResList
                                        [string "Shapeshifting"]
                                  )
                                ]
                            }
                      )
                    ]
                }
            ),
      mutation = pure ResNull,
      subscription = pure ResNull
    }
```
after that you can run it with `Core`
https://github.com/morpheusgraphql/morpheus-graphql/blob/master/morpheus-graphql-core/src/Data/Morpheus/Core.hs
```hs
runApi schema resolver request
````

https://github.com/morpheusgraphql/morpheus-graphql/blob/master/morpheus-graphql-core/test/Spec.hs

**Comment by theobat** [comment]
Hey ! 
I appreciate your advise but the point of this library and the reason why It exists is to use "real" haskell types and to easily navigate between their hasql/sql and graphql representations. The point is I believe haskell should be the central language to use for designing APIs, not graphql, because it's easier to extend haskell types than graphql's.

**Comment by nalchevanidze** [comment]
okey. 
 
but how you going to handle ?

```hs 

data Deity m = Deity
  { name :: m Name,
    power :: m Power 
  }
  deriving (Generic, GQLType)
```
with selection 
```gql 
{ deity { name } }
```
the selection only selects `name`. but field power is required . 
you can't fill only `name`. on resolving. 

how will you trick Haskell type checker ?

i think morpheus should then allow. Dynamic Resolvers. something like that.

```hs
data Dynamic a = Dynamic {  unpack :: ResModel }
```
where morpheus will unpack its ResModel.  instead of deriving resolvers from `Deity` 

```hs
deityResolverSQL :: DeityArgs -> Resolver o e m (Dynamic Deity)
deityResolverSQL args = Dynamic <$> massaliaSQLSelector args
```

**Comment by nalchevanidze** [comment]
what d you think?

**Comment by theobat** [comment]
Yes that's an interesting question there are several possibilities. Before I found morpheus-graphql I wanted to create my own graphql library where all the steps would be embedded in haskell types (parsing, validation etc), through type families & generics to prevent this exact problem from happening, but I abandoned for now (others have tried I reckon: https://github.com/JonathanLorimer/weft, and this: https://reasonablypolymorphic.com/erdos).

My opinion for now is that users should provide default values for their types, and thus, in your example, it would be fine, as long as the `Power` type can have a reasonable default value (I recognize it's not always possible, but it's a simple workaround, and it works for me, so far).

Another possibility is to not instantiate the field, and abandon type safety a little bit. I don't like this option.

Of course I'd like it better if I could have a proper type with all the possible combinations of requests for a type (all valid combination of absence or presence of a field), but that's for the future; if and when there's a deep embedding of graphql in haskell.

**Comment by theobat** [comment]
Also I should add that contrary to graphql's frequent use, I do not believe that every type field should get a resolver. Graphql is very very open about this, but this library mostly assumes that the types **below** the one that is resolved, should don't have resolvers, they should merely be data nodes.
This is in contrast to the example you provided where Deity's fields both have resolvers.
I find it easier to have "data nodes" and "query/mutation/subscription nodes" (nodes = graphql aware datatypes). But I realize this is quite restrictive compared to what graphql can offer.
